package com.example.homework.mapper;

import com.example.homework.model.Category;
import com.example.homework.model.CategoryExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

@Mapper
public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_category
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    long countByExample(CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_category
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    int deleteByExample(CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_category
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_category
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    int insert(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_category
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    int insertSelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_category
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    List<Category> selectByExampleWithRowbounds(CategoryExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_category
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    List<Category> selectByExample(CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_category
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    Category selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_category
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    int updateByExampleSelective(@Param("record") Category record, @Param("example") CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_category
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    int updateByExample(@Param("record") Category record, @Param("example") CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_category
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    int updateByPrimaryKeySelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_category
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    int updateByPrimaryKey(Category record);
}