package com.example.homework.mapper;

import com.example.homework.model.Item;
import com.example.homework.model.ItemExample;
import com.example.homework.model.ItemWithBLOBs;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface ItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_item
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    long countByExample(ItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_item
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    int deleteByExample(ItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_item
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_item
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    int insert(ItemWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_item
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    int insertSelective(ItemWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_item
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    List<ItemWithBLOBs> selectByExampleWithBLOBsWithRowbounds(ItemExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_item
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    List<ItemWithBLOBs> selectByExampleWithBLOBs(ItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_item
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    List<Item> selectByExampleWithRowbounds(ItemExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_item
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    List<Item> selectByExample(ItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_item
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    ItemWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_item
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    int updateByExampleSelective(@Param("record") ItemWithBLOBs record, @Param("example") ItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_item
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") ItemWithBLOBs record, @Param("example") ItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_item
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    int updateByExample(@Param("record") Item record, @Param("example") ItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_item
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    int updateByPrimaryKeySelective(ItemWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_item
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(ItemWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_item
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    int updateByPrimaryKey(Item record);
}