package com.example.homework.mapper;

import com.example.homework.model.News;
import com.example.homework.model.NewsExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface NewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_news
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    long countByExample(NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_news
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    int deleteByExample(NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_news
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_news
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    int insert(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_news
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    int insertSelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_news
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    List<News> selectByExampleWithRowbounds(NewsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_news
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    List<News> selectByExample(NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_news
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    News selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_news
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    int updateByExampleSelective(@Param("record") News record, @Param("example") NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_news
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    int updateByExample(@Param("record") News record, @Param("example") NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_news
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    int updateByPrimaryKeySelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_news
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    int updateByPrimaryKey(News record);
}