package com.example.homework.mapper;

import com.example.homework.model.Slide;
import com.example.homework.model.SlideExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface SlideMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_slide
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    long countByExample(SlideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_slide
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    int deleteByExample(SlideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_slide
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_slide
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    int insert(Slide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_slide
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    int insertSelective(Slide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_slide
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    List<Slide> selectByExampleWithRowbounds(SlideExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_slide
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    List<Slide> selectByExample(SlideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_slide
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    Slide selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_slide
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    int updateByExampleSelective(@Param("record") Slide record, @Param("example") SlideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_slide
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    int updateByExample(@Param("record") Slide record, @Param("example") SlideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_slide
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    int updateByPrimaryKeySelective(Slide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jq_slide
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    int updateByPrimaryKey(Slide record);
}