package com.example.homework.mapper;

import com.example.homework.model.TypeType;
import com.example.homework.model.TypeTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TypeTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typetype
     *
     * @mbg.generated Wed Dec 18 15:42:03 CST 2019
     */
    long countByExample(TypeTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typetype
     *
     * @mbg.generated Wed Dec 18 15:42:03 CST 2019
     */
    int deleteByExample(TypeTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typetype
     *
     * @mbg.generated Wed Dec 18 15:42:03 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typetype
     *
     * @mbg.generated Wed Dec 18 15:42:03 CST 2019
     */
    int insert(TypeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typetype
     *
     * @mbg.generated Wed Dec 18 15:42:03 CST 2019
     */
    int insertSelective(TypeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typetype
     *
     * @mbg.generated Wed Dec 18 15:42:03 CST 2019
     */
    List<TypeType> selectByExampleWithRowbounds(TypeTypeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typetype
     *
     * @mbg.generated Wed Dec 18 15:42:03 CST 2019
     */
    List<TypeType> selectByExample(TypeTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typetype
     *
     * @mbg.generated Wed Dec 18 15:42:03 CST 2019
     */
    TypeType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typetype
     *
     * @mbg.generated Wed Dec 18 15:42:03 CST 2019
     */
    int updateByExampleSelective(@Param("record") TypeType record, @Param("example") TypeTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typetype
     *
     * @mbg.generated Wed Dec 18 15:42:03 CST 2019
     */
    int updateByExample(@Param("record") TypeType record, @Param("example") TypeTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typetype
     *
     * @mbg.generated Wed Dec 18 15:42:03 CST 2019
     */
    int updateByPrimaryKeySelective(TypeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typetype
     *
     * @mbg.generated Wed Dec 18 15:42:03 CST 2019
     */
    int updateByPrimaryKey(TypeType record);
}