package com.example.homework.mapper;

import com.example.homework.model.User;
import com.example.homework.model.UserExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface UserMapper {

    @Select("select * from infomation where id = #{id}")
    public User selectById(Integer id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infomation
     *
     * @mbg.generated Fri Dec 13 08:29:46 CST 2019
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infomation
     *
     * @mbg.generated Fri Dec 13 08:29:46 CST 2019
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infomation
     *
     * @mbg.generated Fri Dec 13 08:29:46 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infomation
     *
     * @mbg.generated Fri Dec 13 08:29:46 CST 2019
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infomation
     *
     * @mbg.generated Fri Dec 13 08:29:46 CST 2019
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infomation
     *
     * @mbg.generated Fri Dec 13 08:29:46 CST 2019
     */
    List<User> selectByExampleWithRowbounds(UserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infomation
     *
     * @mbg.generated Fri Dec 13 08:29:46 CST 2019
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infomation
     *
     * @mbg.generated Fri Dec 13 08:29:46 CST 2019
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infomation
     *
     * @mbg.generated Fri Dec 13 08:29:46 CST 2019
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infomation
     *
     * @mbg.generated Fri Dec 13 08:29:46 CST 2019
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infomation
     *
     * @mbg.generated Fri Dec 13 08:29:46 CST 2019
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infomation
     *
     * @mbg.generated Fri Dec 13 08:29:46 CST 2019
     */
    int updateByPrimaryKey(User record);
}