package com.example.homework.model;

import java.util.Date;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jq_category.id
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jq_category.parent_id
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jq_category.name
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jq_category.status
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jq_category.sort
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jq_category.is_parent
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    private Byte isParent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jq_category.created
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jq_category.updated
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    private Date updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jq_category.id
     *
     * @return the value of jq_category.id
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jq_category.id
     *
     * @param id the value for jq_category.id
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jq_category.parent_id
     *
     * @return the value of jq_category.parent_id
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jq_category.parent_id
     *
     * @param parentId the value for jq_category.parent_id
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jq_category.name
     *
     * @return the value of jq_category.name
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jq_category.name
     *
     * @param name the value for jq_category.name
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jq_category.status
     *
     * @return the value of jq_category.status
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jq_category.status
     *
     * @param status the value for jq_category.status
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jq_category.sort
     *
     * @return the value of jq_category.sort
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jq_category.sort
     *
     * @param sort the value for jq_category.sort
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jq_category.is_parent
     *
     * @return the value of jq_category.is_parent
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public Byte getIsParent() {
        return isParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jq_category.is_parent
     *
     * @param isParent the value for jq_category.is_parent
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public void setIsParent(Byte isParent) {
        this.isParent = isParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jq_category.created
     *
     * @return the value of jq_category.created
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jq_category.created
     *
     * @param created the value for jq_category.created
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jq_category.updated
     *
     * @return the value of jq_category.updated
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jq_category.updated
     *
     * @param updated the value for jq_category.updated
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
}