package com.example.homework.model;

public class ItemWithBLOBs extends Item {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jq_item.content
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jq_item.album
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    private String album;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jq_item.content
     *
     * @return the value of jq_item.content
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jq_item.content
     *
     * @param content the value for jq_item.content
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jq_item.album
     *
     * @return the value of jq_item.album
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public String getAlbum() {
        return album;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jq_item.album
     *
     * @param album the value for jq_item.album
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public void setAlbum(String album) {
        this.album = album == null ? null : album.trim();
    }
}