package com.example.homework.model;

import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;

@Data
public class Item {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jq_item.id
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jq_item.cid
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jq_item.title
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jq_item.sell_point
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    private String sellPoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jq_item.price
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jq_item.num
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jq_item.pic
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jq_item.status
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    private Byte status;
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jq_item.created
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jq_item.updated
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    private Date updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jq_item.id
     *
     * @return the value of jq_item.id
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jq_item.id
     *
     * @param id the value for jq_item.id
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jq_item.cid
     *
     * @return the value of jq_item.cid
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jq_item.cid
     *
     * @param cid the value for jq_item.cid
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jq_item.title
     *
     * @return the value of jq_item.title
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jq_item.title
     *
     * @param title the value for jq_item.title
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jq_item.sell_point
     *
     * @return the value of jq_item.sell_point
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public String getSellPoint() {
        return sellPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jq_item.sell_point
     *
     * @param sellPoint the value for jq_item.sell_point
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public void setSellPoint(String sellPoint) {
        this.sellPoint = sellPoint == null ? null : sellPoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jq_item.price
     *
     * @return the value of jq_item.price
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jq_item.price
     *
     * @param price the value for jq_item.price
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jq_item.num
     *
     * @return the value of jq_item.num
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jq_item.num
     *
     * @param num the value for jq_item.num
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jq_item.pic
     *
     * @return the value of jq_item.pic
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jq_item.pic
     *
     * @param pic the value for jq_item.pic
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jq_item.status
     *
     * @return the value of jq_item.status
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jq_item.status
     *
     * @param status the value for jq_item.status
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jq_item.created
     *
     * @return the value of jq_item.created
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jq_item.created
     *
     * @param created the value for jq_item.created
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jq_item.updated
     *
     * @return the value of jq_item.updated
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jq_item.updated
     *
     * @param updated the value for jq_item.updated
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
}