package com.example.homework.model;

import java.math.BigDecimal;

public class Shop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jq_shop.id
     *
     * @mbg.generated Thu Dec 19 13:40:41 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jq_shop.title
     *
     * @mbg.generated Thu Dec 19 13:40:41 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jq_shop.price
     *
     * @mbg.generated Thu Dec 19 13:40:41 CST 2019
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jq_shop.num
     *
     * @mbg.generated Thu Dec 19 13:40:41 CST 2019
     */
    private Long num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jq_shop.id
     *
     * @return the value of jq_shop.id
     *
     * @mbg.generated Thu Dec 19 13:40:41 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jq_shop.id
     *
     * @param id the value for jq_shop.id
     *
     * @mbg.generated Thu Dec 19 13:40:41 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jq_shop.title
     *
     * @return the value of jq_shop.title
     *
     * @mbg.generated Thu Dec 19 13:40:41 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jq_shop.title
     *
     * @param title the value for jq_shop.title
     *
     * @mbg.generated Thu Dec 19 13:40:41 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jq_shop.price
     *
     * @return the value of jq_shop.price
     *
     * @mbg.generated Thu Dec 19 13:40:41 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jq_shop.price
     *
     * @param price the value for jq_shop.price
     *
     * @mbg.generated Thu Dec 19 13:40:41 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jq_shop.num
     *
     * @return the value of jq_shop.num
     *
     * @mbg.generated Thu Dec 19 13:40:41 CST 2019
     */
    public Long getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jq_shop.num
     *
     * @param num the value for jq_shop.num
     *
     * @mbg.generated Thu Dec 19 13:40:41 CST 2019
     */
    public void setNum(Long num) {
        this.num = num;
    }
}