package com.example.homework.model;

import java.util.Date;

public class Slide {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jq_slide.id
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jq_slide.title
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jq_slide.pic
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jq_slide.status
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jq_slide.sort
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jq_slide.url
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jq_slide.created
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jq_slide.updated
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    private Date updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jq_slide.id
     *
     * @return the value of jq_slide.id
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jq_slide.id
     *
     * @param id the value for jq_slide.id
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jq_slide.title
     *
     * @return the value of jq_slide.title
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jq_slide.title
     *
     * @param title the value for jq_slide.title
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jq_slide.pic
     *
     * @return the value of jq_slide.pic
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jq_slide.pic
     *
     * @param pic the value for jq_slide.pic
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jq_slide.status
     *
     * @return the value of jq_slide.status
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jq_slide.status
     *
     * @param status the value for jq_slide.status
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jq_slide.sort
     *
     * @return the value of jq_slide.sort
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jq_slide.sort
     *
     * @param sort the value for jq_slide.sort
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jq_slide.url
     *
     * @return the value of jq_slide.url
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jq_slide.url
     *
     * @param url the value for jq_slide.url
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jq_slide.created
     *
     * @return the value of jq_slide.created
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jq_slide.created
     *
     * @param created the value for jq_slide.created
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jq_slide.updated
     *
     * @return the value of jq_slide.updated
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jq_slide.updated
     *
     * @param updated the value for jq_slide.updated
     *
     * @mbg.generated Thu Dec 12 15:55:07 CST 2019
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
}